---
services:
  mc:
    image: itzg/minecraft-server:stable-java21-alpine
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "1.21.1"
      MODRINTH_MODPACK: /modpacks/create-adventure-SMP-1.0.0.mrpack
      MODS: |
        https://cdn.modrinth.com/data/IKARgflD/versions/bgR1e0O5/DiagonalFences-v21.1.1-1.21.1-NeoForge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/oOi0CKes/versions/IwUmOLxe/DiagonalWindows-v21.1.1-1.21.1-NeoForge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/FQgc8dib/versions/2k3GCxEt/DiagonalWalls-v21.1.2-1.21.1-NeoForge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/kNxa8z3e/versions/u7BRX44F/mcw-doors-1.1.5-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/B8jaH3P1/versions/jiXRXiSt/mcw-roofs-2.3.2-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/dtWC90iB/versions/Z5V3Ps7S/mcw-furniture-3.4.1-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/GmwLse2I/versions/jVdb0r4W/mcw-mcwfences-1.2.1-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/iP3wH1ha/versions/4t8L0dGP/mcw-mcwstairs-1.0.2-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/n2fvCDlM/versions/StnP0RNi/mcw-trapdoors-1.1.5-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/C7I0BCni/versions/rQUE4LCz/mcw-mcwwindows-2.4.2-mc1.21.1neoforge.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/tagwiZkJ/versions/VEburL70/polymorph-neoforge-1.1.0%2B1.21.1.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/u6dRKJwZ/versions/YAcQ6elZ/jei-1.21.1-neoforge-19.27.0.340.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/uLtxXFVm/versions/30Ayywkn/mcwquark-neoforge-1.21.1-1.6.1.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
        https://cdn.modrinth.com/data/cl5ec0Qm/versions/7SEGJEQj/addonslib-neoforge-1.21.1-1.14.jar?mr_download_reason=standalone&mr_game_version=1.21.1&mr_loader=neoforge
      MODRINTH_EXCLUDE_FILES: |
        polymorph-neoforge-1.2.0+1.21.1.jar
        jei-1.21.1-neoforge-19.27.0.429.jar
      MEMORY: "16384M"
      MAX_MEMORY: "20480M"
      MAX_PLAYERS: "10"
      MOTD: "§6gaming"
      ONLINE_MODE: "false"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Europe/Stockholm"
      DIFFICULTY: "2"
      SIMULATION_DISTANCE: "11"
      VIEW_DISTANCE: "12"
      LEVEL: "pacpack"
      SPAWN_PROTECTION: "0"
      RATE_LIMIT: "0"
      ENFORCE_SECURE_PROFILE: "false"
      STATUS_HEARTBEAT_INTERVAL: "60000"
      #RCON_CMDS_LAST_DISCONNECT: |-
      # Example: run backup command when last player disconnects from the server
      ALLOW_FLIGHT: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SERVER_NAME: "paccao's server"
    volumes:
      - "./mc-data:/data:Z" # :Z for rootless setup
      - ./modpacks:/modpacks:ro
