---
- name: Install git
  ansible.builtin.package:
    name: "git"
    state: present
  become: true
  become_method: doas
  become_user: ansible

- name: Clone repo onto server
  ansible.builtin.git:
    repo: "https://github.com/paccao/minecraft-server.git"
    dest: "/home/{{ minecraft_user }}/"
    update: true
    clone: true
