---
# - name: Install git
#   ansible.builtin.package:
#     name: "git"
#     state: present
#   become: true

- name: create directory
  ansible.builtin.file:
    state: directory
    path: "/home/{{ minecraft_user }}/minecraft-server/"

- name: Clone repo onto server
  ansible.builtin.git:
    repo: "https://github.com/paccao/minecraft-server.git"
    dest: "/home/{{ minecraft_user }}/minecraft-server/"
    update: true
    clone: true
