---
- name: copy local data onto server
  ansible.builtin.copy:
    src: "{{ local_src }}" # Specifically without trailing slash here in order to copy every file recursively, including the directory
    dest: "{{ destination_path }}/"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: preserve
