---
data_dir: "data-v2"
backups_dir: "backups"
backup_mod_path: "simplebackups"
mcserver_level_name: "pacpack"
project_path: "/home/ansible/minecraft-server"
local_project_path: "/home/plum/c/minecraft-server"
minecraft_user: "ansible"
