---
- name: Create backup dir
  ansible.builtin.file:
    state: directory
    path: "{{ project_path }}/{{ backup_dir }}"
    owner: 100999
    group: 100999
    mode: 0755
  become: true
  tags: always

- name: Datadir backup
  ansible.posix.synchronize:
    src: "{{ project_path }}/{{ data_dir }}/"
    # stored in backups/
    dest: "{{ project_path }}/{{ backup_dir }}/{{ data_dir }}_{{ now(fmt='%Y-%m-%d %H:%M') }}/"
    dirs: true
    archive: true
    perms: true
    owner: true
    group: true
    rsync_opts:
      - "--numeric-ids"
      - "--exclude={{ backup_mod_path }}/**/*.zip"
  become: true
  when:
    - "'partial_datadir' in ansible_run_tags or 'full_backup' in ansible_run_tags or 'all' in ansible_run_tags"

- name: Backup simplebackups zip files
  ansible.posix.synchronize:
    src: "{{ project_path }}/{{ data_dir }}/{{ backup_mod_path }}/{{ minecraft_level_name }}/"
    # stored in backups/
    dest: "{{ project_path }}/{{ backup_dir }}/"
    dirs: true
    archive: true
    perms: true
    owner: true
    group: true
    rsync_opts:
      - "--numeric-ids"
  become: true
  when:
    - "'partial_datadir' not in ansible_run_tags or 'full_backup' in ansible_run_tags or 'all' in ansible_run_tags"
