---
- name: Enable alpine community repositories
  ansible.builtin.template:
    src: repositories.j2
    dest: /etc/apk/repositories
    mode: "0644"

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "podman"
    - "podman-compose"
    - "iptables"

- name: Enable cgroups service # Required for non-root podman
  ansible.builtin.service:
    name: cgroups
    enabled: true
    state: started

- name: Enable tun kernel module and set ansible user subuid and subgid
  raw: |
    modprobe tun
    echo tun >>/etc/modules
    echo {{ future_ansible_user }}:100000:65536 >/etc/subuid
    echo {{ future_ansible_user }}:100000:65536 >/etc/subgid

- name: Enable podman service
  ansible.builtin.service:
    name: podman
    enabled: true
    state: started
