---
- name: Local backup of minecraft server data
  hosts: localhost
  vars:
    project_path: "/home/plum/c/minecraft-server"

  tasks:
    - ansible.builtin.include_role:
        name: backup
        apply:
          tags:
            - partial_datadir
            - full_backup
      tags:
        - partial_datadir
        - full_backup
