---
- name: Take a local backup
  ansible.posix.synchronize:
    src: "{{ local_path }}/{{ data_dir }}/"
    # stored in backups/
    # dest: "{{ local_path }}/{{ backup_dir }}/{{ data_dir }}_{{ now(fmt='%Y-%m-%d %H:%M') }}"
    dest: "{{ local_path }}/tmp_backup_test/{{ data_dir }}_{{ now(fmt='%Y-%m-%d %H:%M') }}"
    archive: true
    perms: true
    owner: true
    group: true
    rsync_opts:
      - "--numeric-ids"
      - "--exclude={{ backup_mod_path }}/**/*.zip"
  delegate_to: localhost
  become: true
