---
- name: Install base packages
  raw: |
    apk update
    apk add --no-cache python3
  changed_when: true

- name: Create ansible user if missing
  ansible.builtin.user:
    name: "{{ future_ansible_user }}"
    state: present
    create_home: true
    shell: /bin/ash
    groups: wheel
    append: true
  register: user_created

- name: Set password only if user was created
  ansible.builtin.shell: "echo '{{ future_ansible_user }}:{{ future_ansible_user_password }}' | chpasswd"
  when: user_created.changed
  no_log: true

- name: Create SSH directory
  ansible.builtin.file:
    state: directory
    owner: "{{ future_ansible_user }}"
    group: "{{ future_ansible_user }}"
    mode: "0700"
    path: "/home/{{ future_ansible_user }}/.ssh"

- name: Set up SSH key on remote
  ansible.posix.authorized_key:
    user: "{{ future_ansible_user }}"
    state: present
    key: "{{ lookup('file', playbook_dir ~ '/keys/pi5-alpine-1.pub') }}"
