---
- name: Create ansible user if missing
  ansible.builtin.user:
    name: "{{ minecraft_user }}"
    state: present
    create_home: true
    shell: /bin/ash
    append: true
    password: "{{ minecraft_user_password }}"
